### ISSUE TITLE
Combined Crafter mysteriously eats recipe holder in Unpackager

### ISSUE THREAD

**Issue by Fiona** [TheLMiffy1111/PackagedExCrafting#1]
Hi, in Omnifactory we've upgraded PackagedAuto to 1.0.2.9 and PackagedExCrafting to 1.0.1.1 and are finding a few weird behaivours.

Quite a critical one is that the recipe holder that is placed in an Unpackager adjacent to a Combined Crafter completely disappears after a single craft - along with any packages waiting to unpack. 

You can request say, 10 items from AE2. 10 packages will be made and then they'll start being sent to the Unpackager. It will have put about 3 packages into the Unpackager when the first craft is complete and suddenly everything in it will disappear, as if the block state was completely reset. The packages that hadn't made it to the Unpackager yet will be sent back to the AE2 system and AE2 will be waiting for the full set of crafts to finish. At this point the item will no longer be craftable from AE2.

If you, for instance, manually plop a bunch of packages into the Unpackager, they will all be destroyed as soon as the first craft is complete, again along with the recipe holder.

I've tried a whole bunch of set-ups and I can replicate it everytime. No matter what happens I can't stop it eating everything.

**Comment by Exaxxion** [comment]
While I haven't experienced this exact behavior, I have seen similar things where the Package Recipe Holders completely disappear from the Packager/Unpackager when I exit and load back into a world.

AE Channels are off; my setup is just a creative energy cell, a drive with a formatted creative cell, a Terminal on a piece of fluix cable, a Packager, an Unpackager, a 5x5 crafter, and a 9x9 crafter. I have two recipes per pattern holder (one for each connected crafter) with one copy in the Packager and one copy in the Unpackager.

Within the loaded world, I've used them mostly fine (except for the "randomly disappearing packages" bug I reported a while ago).

**Comment by TheLMiffy1111** [comment]
Are there any logs available?

**Comment by Fiona** [comment]
Ooo fun, yes this just popped up in the log as I tried it again.

```
[09:52:03] [Server thread/FATAL] [FML]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  LogisticsPipesCoreLoader (logisticspipes-0.10.2.216.jar)
  CreativePatchingLoader (CreativeCore_v1.9.90_mc1.12.2.jar)
  RBLoadingPlugin (RealBench-1.12.2-1.3.3.jar)
  BedPatch (bedpatch-2.2-1.12.2.jar)
  LittlePatchingLoader (LittleTiles_v1.5.0-pre198_mc1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.7.0-208-universal.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.73-core.jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.20-release.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
Contact their authors BEFORE contacting forge

// Ouch. That hurt :(

Time: 3/13/20 9:52 AM
Description: Ticking block entity

java.lang.NoSuchMethodError: com.blakebr0.extendedcrafting.crafting.CombinationRecipe.getCost()I
	at thelm.packagedexcrafting.recipe.RecipeInfoCombination.getEnergyRequired(RecipeInfoCombination.java:116)
	at thelm.packagedexcrafting.tile.TileCombinationCrafter.acceptPackage(TileCombinationCrafter.java:124)
	at thelm.packagedauto.tile.TileUnpackager.emptyTrackers(TileUnpackager.java:161)
	at thelm.packagedauto.tile.TileUnpackager.func_73660_a(TileUnpackager.java:96)
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at thelm.packagedexcrafting.recipe.RecipeInfoCombination.getEnergyRequired(RecipeInfoCombination.java:116)
	at thelm.packagedexcrafting.tile.TileCombinationCrafter.acceptPackage(TileCombinationCrafter.java:124)
	at thelm.packagedauto.tile.TileUnpackager.emptyTrackers(TileUnpackager.java:161)
	at thelm.packagedauto.tile.TileUnpackager.func_73660_a(TileUnpackager.java:96)

-- Block entity being ticked --
Details:
	Name: packagedauto:unpackager // thelm.packagedauto.tile.TileUnpackager
	Block type: ID #571 (tile.packagedauto.unpackager // thelm.packagedauto.block.BlockUnpackager // packagedauto:unpackager)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-210,72,197), Chunk: (at 14,4,5 in -14,12; contains blocks -224,0,192 to -209,255,207), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #571 (tile.packagedauto.unpackager // thelm.packagedauto.block.BlockUnpackager // packagedauto:unpackager)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 3.10.0
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 67445888 bytes (64 MB) / 2145386496 bytes (2046 MB) up to 2290089984 bytes (2184 MB)
	JVM Flags: 9 total; -XX:+OptimizeStringConcat -XX:OnOutOfMemoryError=curl https://api.creeper.host/callbacks/minecraft/outofmemory.php?instance=mc-5e380990b71a4 -k -XX:OnError=curl http://api.creeper.host/callbacks/minecraft/crash.php?instance=mc-5e380990b71a4 -k -XX:-UseCompressedOops -Xmx2496M -XX:+UseGCOverheadLimit -XX:ParallelGCThreads=3 -XX:+AggressiveHeap -XX:+AggressiveOpts
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 153 mods loaded, 153 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
```

**Comment by Fiona** [comment]
We're using Extended Crafting 1.5.6.

**Comment by Fiona** [comment]
Okay I just noticed that the dependency in your Gradle build is Extended Crafting 1.5.2. I just tried rolling back and I'm no longer getting this issue.

Can you confirm that the latest version of Extended Crafting you support is 1.5.2?

**Comment by TheLMiffy1111** [comment]
The latest version of PackagedExCrafting should work up to version 1.5.5 of Extended Crafting.
1.5.6 changed the energy requirement of Combination Crafting from an int to a long.

**Comment by Fiona** [comment]
Right-o so I upgraded to the new PEC and EC. And my server dies and doesn't let anyone join.

This is the third time this has happened to me, it requires me to roll back to a much much older backup and then eventually happens again a short while later. Interacting with PA in some way seems to trigger it.

Here's a pastebin of the error: https://pastebin.com/2nVK8AAa

Now although PEC or EC isn't mentioned, the server happily starts up if I rollback to EC 1.5.4. So it's certainly part of the picture. What's the version of AE2 we should be using? We've currently using rv6-stable-7.

**Comment by Fiona** [comment]
Probably AE2 related and nothing to do with PEC or PA. Fix looks fine, thanks TheLMifffy1111 :) You can close this now.
