### ISSUE TITLE
All the blocks take forever to mine, even with a netherite pickaxe

### ISSUE THREAD

**Issue by vizthex123** [TheLMiffy1111/PackagedExCrafting#13]
Please reduce their mining times to something more reasonable. I'd say copying the mining time s of each extended crafting table would be good.

I'm playing the 1.18.2 version, but assume this is an issue for all of them.

**Comment by TheLMiffy1111** [comment]
Fixed

**Comment by vizthex123** [comment]
noice, thanks.
