### ISSUE TITLE
Game crashes when crafting any recipe using the combination package crafter

### ISSUE THREAD

**Issue by SmileyFace799** [TheLMiffy1111/PackagedExCrafting#14]
I'm currently playing Enigmatica 2 Expert (1.12.2), and added this mod as it's very handy for lategame. However, when crafting charged draconium blocks (or any recipe in the combination package crafter), the game crashes, and gives me the following error:
```
The game crashed whilst ticking block entity
Error: java.lang.NoSuchMethodError: com.blakebr0.extendedcrafting.crafting.CombinationRecipe.getCost()J
Exit Code: -805306369
```
Any idea why, or how to fix this?

**Comment by TheLMiffy1111** [comment]
Is it possible for you to update Extended Crafting
