### ISSUE TITLE
java.lang.NoSuchMethodError: com.blakebr0.extendedcrafting.crafting.CombinationRecipe.getCost()

### ISSUE THREAD

**Issue by ghost** [TheLMiffy1111/PackagedExCrafting#2]
Forge version: 14.23.5.2847
Mod version: 1.12.2-1.0.1.2
--------------------------------------------INFO---------------------------------------
When i right click the packaged combination core it crashes.

Crash log: https://paste.ubuntu.com/p/RTddHgGN5D/

**Comment by TheLMiffy1111** [comment]
PackagedExCrafting 1.0.1.2 requires Extended Crafting 1.5.6

**Comment by TheLMiffy1111** [comment]
How did you even get this to run
Extended Crafting 1.5.6 should be required

**Comment by ghost** [comment]
Downgraded the version and worke
