### ISSUE TITLE
Recipe for Basic Package Crafter broken

### ISSUE THREAD

**Issue by aaronhowser1** [TheLMiffy1111/PackagedExCrafting#9]
This is using `PackagedExCrafting-1.16.5-2.0.0.2`. JEI shows no recipe for it.

**Comment by TheLMiffy1111** [comment]
It's intentional that the basic package crafter is uncraftable if AE2 is present as I believe that 3x3 recipes exclusive to the extended crafting tables are not a common usage of the mod.
